---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: nginx-ingress
  namespace: ingress
spec:
  releaseName: nginx-ingress
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: nginx-ingress
  values:
    controller:
      service:
        type: "NodePort"
        nodePorts:
          http: "31125"
          https: "30984"
      metrics:
        enabled: true
    controller:
      stats:
        enabled: true 
