version: '3'
services:
  rancher:
    image: "rancher/rancher:v2.4.2"
    ports:
      - "80:80"
      - "443:443"
    command: --no-cacerts
    restart: unless-stopped
    volumes:
      - /etc/letsencrypt/archive/dash.qubernetes.com/:/etc/rancher/ssl/
      - /root/rancher/data:/var/lib/rancher
    environment:
      - SSL_CERT_DIR="/etc/rancher/ssl
