version: '3.7'
services:
  rancher:
    image: "rancher/rancher:v2.4.2"
    ports:
      - "80:80"
      - "443:443"
    command: --no-cacerts
    restart: unless-stopped
    volumes:
      - type: bind 
        source: /etc/letsencrypt/archive/rancher.stackmasters.com/fullchain1.pem
        target: /etc/rancher/ssl/cert.pem
        read_only: true
      - type: bind 
        source: /etc/letsencrypt/archive/rancher.stackmasters.com/privkey1.pem
        target: /etc/rancher/ssl/key.pem
        read_only: true
      - type: bind 
        source: /root/rancher/data 
        target: /var/lib/rancher
    environment:
      - SSL_CERT_DIR="/etc/rancher/ssl
