nodes:
- address: cloud.stackmasters.com
  port: "22"
  internal_address: 192.168.178.2
  role:
  - controlplane
  - etcd
  - worker
  hostname_override: ""
  user: alessandro
  docker_socket: ""
  ssh_key: ""
  ssh_key_path: ""
  ssh_cert: ""
  ssh_cert_path: ""
  labels: {}
  taints: []
- address: box
  port: "22"
  internal_address: 192.168.178.9
  role:
  - worker
  hostname_override: ""
  user: alessandro
  docker_socket: ""
  ssh_key: ""
  ssh_key_path: ""
  ssh_cert: ""
  ssh_cert_path: ""
  labels: {}
  taints: []
- address: nuc1
  port: "22"
  internal_address: 192.168.178.5
  role:
  - worker
  hostname_override: ""
  user: alessandro
  docker_socket: ""
  ssh_key: ""
  ssh_key_path: ""
  ssh_cert: ""
  ssh_cert_path: ""
  labels: {}
  taints: []
- address: nuc2
  port: "22"
  internal_address: 192.168.178.6
  role:
  - worker
  hostname_override: ""
  user: alessandro
  docker_socket: ""
  ssh_key: ""
  ssh_key_path: ""
  ssh_cert: ""
  ssh_cert_path: ""
  labels: {}
  taints: []
services:
  etcd:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
    external_urls: []
    ca_cert: ""
    cert: ""
    key: ""
    path: ""
    uid: 0
    gid: 0
    snapshot: true
    retention: ""
    creation: ""
    backup_config:
      enabled: true
      interval_hours: 12
      retention: 3
      safe_timestamp: false
  kube-api:
    image: ""
    extra_args:
      feature-gates: EphemeralContainers=true
      oidc-client-id: spn:5bd13b05-c17a-4589-8a61-f2185ab7831f
      oidc-groups-claim: groups
      oidc-issuer-url: https://sts.windows.net/a68cdba5-68a4-49a3-8a42-2823316db54f/
      oidc-username-claim: oid
    extra_binds: []
    extra_env: []
    service_cluster_ip_range: ""
    service_node_port_range: ""
    pod_security_policy: false
    always_pull_images: false
    secrets_encryption_config:
      enabled: true
      custom_config: null
    audit_log: null
    admission_configuration: null
    event_rate_limit: null
  kube-controller:
    image: ""
    extra_args:
      feature-gates: EphemeralContainers=true
    extra_binds: []
    extra_env: []
    cluster_cidr: ""
    service_cluster_ip_range: ""
  scheduler:
    image: ""
    extra_args:
      feature-gates: EphemeralContainers=true
    extra_binds: []
    extra_env: []
  kubelet:
    image: ""
    extra_args:
      feature-gates: EphemeralContainers=true
      max-pods: "250"
    extra_binds: []
    extra_env: []
    cluster_domain: cluster.local
    infra_container_image: ""
    cluster_dns_server: ""
    fail_swap_on: false
    generate_serving_certificate: false
  kubeproxy:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
network:
  plugin: canal
  options: {}
  mtu: 0
  node_selector: {}
  update_strategy: null
authentication:
  strategy: x509
  sans:
  - nas.stackmasters.com
  webhook: null
addons: ""
addons_include: []
system_images:
  etcd: ""
  alpine: ""
  nginx_proxy: ""
  cert_downloader: ""
  kubernetes_services_sidecar: ""
  kubedns: ""
  dnsmasq: ""
  kubedns_sidecar: ""
  kubedns_autoscaler: ""
  coredns: ""
  coredns_autoscaler: ""
  nodelocal: ""
  kubernetes: rancher/hyperkube:v1.17.5-rancher1
  flannel: ""
  flannel_cni: ""
  calico_node: ""
  calico_cni: ""
  calico_controllers: ""
  calico_ctl: ""
  calico_flexvol: ""
  canal_node: ""
  canal_cni: ""
  canal_flannel: ""
  canal_flexvol: ""
  weave_node: ""
  weave_cni: ""
  pod_infra_container: ""
  ingress: ""
  ingress_backend: ""
  metrics_server: ""
  windows_pod_infra_container: ""
ssh_key_path: /home/alessandro/.ssh/id_rsa
ssh_cert_path: ""
ssh_agent_auth: false
authorization:
  mode: ""
  options: {}
ignore_docker_version: true
kubernetes_version: v1.17.5-rancher1-1
private_registries: []
ingress:
  provider: none
  options: {}
  node_selector: {}
  extra_args: {}
  dns_policy: ""
  extra_envs: []
  extra_volumes: []
  extra_volume_mounts: []
  update_strategy: null
cluster_name: rancher-home
cloud_provider:
  name: ""
prefix_path: ""
addon_job_timeout: 0
bastion_host:
  address: ""
  port: ""
  user: ""
  ssh_key: ""
  ssh_key_path: ""
  ssh_cert: ""
  ssh_cert_path: ""
monitoring:
  provider: ""
  options: {}
  node_selector: {}
  update_strategy: null
  replicas: null
restore:
  restore: false
  snapshot_name: ""
dns: null
upgrade_strategy:
  max_unavailable_worker: ""
  max_unavailable_controlplane: ""
  drain: false
  node_drain_input: null
