---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: nfs-client
  namespace: nfs-client
spec:
  releaseName: nfs-client
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: nfs-client
  values:
    nfs:
      server: "192.168.178.4"
      mountOptions: "{nfsvers=4}"
      path: "/volume1/NFS"
    storageClass:
      defaultClass: true
