---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: flux-dev
  namespace: flux-dev
spec:
  releaseName: fluxdev
  chart:
    repository: https://charts.fluxcd.io
    name: flux
    version: 1.3.0
  values:
    nameOverride: fluxdev
    allowedNamespaces: []
    serviceAccount:
      name: flux-dev-sa
    clusterrole:
      create: false
    git:
      url: "https://github.com/ams0/flux-dev.git"
      readonly: true
      path: "apps"
      pollInterval: "1m"
    sync:
      state: "secret"
