{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "datadog-secret",
    "namespace": "datadog",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "datadog-secret",
        "namespace": "datadog",
        "creationTimestamp": null
      }
    },
    "encryptedData": {
      "api-key": "AgAaNs/Y1yI89BB1zDq8pV4ncILPdhCv7GiSF7BNcOR/rJzCN5X4wliy6F8/Yf8kupOKvnWi/B9oGuGwI8tNUXpD5r7SQATEzox3R8H8S00Tpjx50Ij17RhR0SZ6GClxZL/A/B47Tq/UnLLf3DsYcVxISDSD1vOoQewpRMaR6c3AV0Bkmo3lzMS7a1hprtelJwogZKaEDgM3ElBwkLqWqWQSHu7hd5qG1ZvnY3/1H6IdyE8e8htIDZ+QmS7yNujE5mlwdBv3eZ/G38jUQs6RalOTr68oUXXHLbaGi3mZVOh3HhCgW3Y06YaQUir/t+RsTGqmP9DmZwNNUbzNDzj9rkKjHOrZFF8nRH0xpHl5OVRlm3Vlk7k4VS1t9XJlZnFIdOSARerKreENXR0goqP1P8Ajq+3Uou80nmSeIQjFrSt1zrNAmuRW5zgXTJZvNW+0Z52+1aCxMgzrnFPuXy+akqFyYYpgXb0OqcKaNFKaPelaoVkcwDKLVGggjEdPzGmKFqYFC64EZvMUGUjLbOiRjAVdKzNPlcxgej0SRYWVvkya91QNZwEw1sRnjf3SK1o679fjL5i/6PzMYu1qYXTTQhhhpK8iuI2a4CGQhJE9v1IwNgRaHkjk7p+QsdR9ngyRmHe3oxLaEg73ZiV1FdsfrJO3xwx3Z3XRxlX/lEBThcm6ZtAm71Qe+JDPz5mIpz/VDyYCmwhT/b5E+q9DHJB4I+1ItmT7q8we44dRuNKNnA3hVw=="
    }
  }
}
