name: CI

on:
  pull_request:
    paths:
    - 'manifests/**'
  push:
    paths:
    - 'manifests/**'

jobs:
  kubeval:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Validate manifests
        uses: stefanprodan/kube-tools@v1
        with:
          command: |
            echo "Validating manifests"
            kubeval --ignore-missing-schemas -d manifests/