name: CI

on: [push, pull_request]
  paths:
  - 'manifests/**'

jobs:
  kubeval:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Validate manifests
        uses: stefanprodan/kube-tools@v1
        with:
          command: |
            echo "Validating manifests"
            kubeval -d manifests/